apiVersion: skaffold/v2alpha3
kind: config
deploy: 
  kubectl:
    manifest:
      - ./infra/k8s/*
build:
  local:
    push: false
  artefacts:
    - image: martindimitrov/auth
      context: auth
      docker:
        dockerFile: Dockerfile
      sync:
        manual: 
          - src: "src/**/*.ts"
          dest: .
    - image: martindimitrov/ticketing-client
      context: client
      docker:
        dockerFile: Dockerfile
      sync:
        manual: 
          - src: "src/**/*.ts"
          dest: .
    - image: martindimitrov/tickets
      context: tickets
      docker:
        dockerFile: Dockerfile
      sync:
        manual: 
          - src: "src/**/*.ts"
          dest: .
    - image: martindimitrov/orders
      context: orders
      docker:
        dockerFile: Dockerfile
      sync:
        manual: 
          - src: "src/**/*.ts"
          dest: .
    - image: martindimitrov/expiration
      context: expiration
      docker:
        dockerFile: Dockerfile
      sync:
        manual: 
          - src: "src/**/*.ts"
          dest: .