apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: expiration
    template:
      metadata:
        labels:
          app: expiration
      spec:
        container:
          - name: expiration
            image: martindimitrov/expiration
            env:
              - name: NATS_CLIENT_ID
                valueFrom:
                  filedRef:
                    filedPath: metadata.name
              - name: NATS_URL
                value: 'http://nats-srv:4222'
              - name: NATS_CLUSTER_ID
                value: ticketing
              - name: REDIS_HOST
                value: 'expiration-redis-srv'